import type { NextPage } from "next";
import Head from "next/head";

const Main: NextPage = () => {
    return (
        <div>
            {/* <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head> */}
            <section>
                <h1>Main</h1>
            </section>
        </div>
    );
};

export default Main;
