import type { NextPage } from "next";
import Head from "next/head";
import Suggested from "./suggested";
import Trends from "./trends";

const RightSide: NextPage = () => {
    return (
        <div>
            {/* <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head> */}
            <section className="pt-1 h-screen drop-shadow-md">
               <Suggested/>
               <Trends/>
            </section>
        </div>
    );
};

export default RightSide;
