import type { NextPage } from "next";
import React, { memo } from "react";
import Suggested from "../ExploreUser";
import ActiveFriends from "./activeFriends";

const RightSide: NextPage = () => {
    return (
        <div>
            {/* <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head> */}
            <section className="pt-1 drop-shadow-md">
                <Suggested />
                <ActiveFriends />
            </section>
        </div>
    );
};

export default memo(RightSide);
