[tool.poetry]
name = "backend_python"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
ecapture = "^0.1.8"
wolframalpha = "^5.0.0"
comtypes = "^1.1.10"
ChatterBot = "^1.1.0"
spacy = "^2.1"

json-tricks = "^3.15.5"
imageio-ffmpeg = "^0.4.5"
chatterbot-corpus = {git = "https://github.com/gunthercox/chatterbot-corpus.git"}




















[tool.poetry.dev-dependencies]




======assistant======

chatbotAI = "^0.3.1"
wikipedia = "^1.4.0"

======emotions============object======

tensorflow = "^2.6.0"
mxnet = "^1.8.0"
matplotlib = "^3.4.3"
scipy = "^1.7.1"
pandas = "^1.3.2"
opencv-python-headless = "4.5.1.48"


======recognition======

numpy = "1.21.1"
opencv-python = "^4.5.3"
face-recognition = "1.3.0"
opencv-contrib-python = "^4.5.3"




======text======

waitress = "^2.0.0"


======video======

Pillow = "^8.3.2"
breadability = "0.1.20"
certifi = "2017.7.27.1"
chardet = "3.0.4"
decorator = "4.0.11"
docopt = "0.6.2"
idna = "2.6"
imageio = "2.2.0"  "2.9.0"
lxml = "^4.6.3"
nltk = "3.2.5"
olefile = "0.44"
pysrt = "1.1.1"
pytube = "6.4.2"
requests = "2.18.4" / "^2.26.0"
six = "1.11.0" / "1.15.0"
sumy = "0.7.0" / "0.8.1"
tqdm = "4.11.2" / "4.27"
urllib3 = "1.22"
youtube_dl = "^2021.6.6"
moviepy = "<=2.0.0"
Flask = "^2.0.1"



