import type { NextPage } from "next";
import Head from "next/head";
import { memo } from "react";
import Main from "../components/home/main";
import Layout from "../components/Layout";
const Index: NextPage = () => {
    return (
        <>
            <Head>
                <title>Lite Media</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link
                    rel="icon"
                    href="/logo.svg"
                    sizes="any"
                    type="image/svg+xml"
                />
            </Head>
            <Layout title="home">
                <Main />
            </Layout>
        </>
    );
};

export default memo(Index);
