import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { memo } from "react";
import useSWR from "swr";
import SuggestedUserBody from "../components/ExploreUser/suggestedUserBody";
import Layout from "../components/Layout";
import UserLoadingSkeleton from "../components/progress/UserLoadingSkeleton";
import { GetState } from "../state/stateProvider";
import { NOTIFICATION_ADD } from "../state/types";
import { fetcher, NODE_SERVER, REFRESH_INTERVAL } from "../util";

const Index: NextPage = () => {
    const { uid, dispatch } = GetState();
    const router = useRouter();

    const { data, error } = useSWR(NODE_SERVER(`/user/all/${uid}`), fetcher, {
        refreshInterval: REFRESH_INTERVAL,
    });
    if (error) {
        dispatch({
            type: NOTIFICATION_ADD,
            payload: { type: "error", text: error },
        });
    }

    const searchedUser =
        data?.users?.length > 0 &&
        data?.users?.filter((v: any) =>
            v.name.fullName.toLowerCase().includes(router.query.like)
        );

    return (
        <>
            <Head>
                <title>Searched Results | Lite Media</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link
                    rel="icon"
                    href="/logo.svg"
                    sizes="any"
                    type="image/svg+xml"
                />
            </Head>
            <Layout title="Searched Result">
                {searchedUser ? (
                    searchedUser?.length > 0 ? (
                        searchedUser?.map((user: any) => (
                            <div key={user._id}>
                                <SuggestedUserBody user={user} />
                                <hr className="border-b border-indigo-300" />
                            </div>
                        ))
                    ) : (
                        <div className="flex items-center justify-center h-full">
                            <h3>User Not found</h3>
                        </div>
                    )
                ) : (
                    <UserLoadingSkeleton />
                )}
            </Layout>
        </>
    );
};

export default memo(Index);
