import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import Layout from "../components/Layout";
import SettingBody from "../components/settings";
const Index: NextPage = () => {
    return (
        <>
            <Head>
                <title>Settings | Lite Media</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link
                    rel="icon"
                    href="/logo.svg"
                    sizes="any"
                    type="image/svg+xml"
                />
            </Head>
            <Layout title="settings">
                <SettingBody />
            </Layout>
        </>
    );
};

export default Index;
